# Generated by Django 6.1 on 2026-08-11 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshTokenRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retired_jti', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('rotated_at', models.DateTimeField(auto_now_add=True)),
                ('issued_access_token', models.TextField()),
                ('issued_refresh_token', models.TextField()),
                ('issued_refresh_jti', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_rotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='accounts_re_expires_6ed5d6_idx')],
            },
        ),
    ]
