# Generated by Django 6.1 on 2026-08-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_refreshtokenrotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sms_carrier',
            field=models.CharField(blank=True, choices=[('verizon', 'Verizon'), ('att', 'AT&T'), ('tmobile', 'T-Mobile'), ('sprint', 'Sprint'), ('uscellular', 'US Cellular'), ('boost', 'Boost Mobile'), ('cricket', 'Cricket Wireless'), ('metropcs', 'Metro by T-Mobile'), ('googlefi', 'Google Fi')], default='', max_length=32),
        ),
    ]
