# Generated by Django 6.1 on 2026-08-11 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start'],
                'constraints': [models.CheckConstraint(condition=models.Q(('start__lt', models.F('end'))), name='blocked_time_start_before_end')],
            },
        ),
    ]
